Vagrant::Config.run do |config|
  #
  # config relative to the ssh connection, here we want to forward X
  #
  config.ssh.forward_x11 = true

  #
  # vm relative setup
  #

  vm_type = 'plain'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'quantal'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://cloud-images.ubuntu.com/quantal/current/quantal-server-cloudimg-vagrant-i386-disk1.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.quantal32.vagrantup.com"
  config.vm.network :hostonly, "192.168.33.10"

  # Forward a port from the guest to the host (id, guest port, host port)
  config.vm.forward_port 80, 8080, :auto => true

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-ubuntu32.pp"
    puppet.module_path = '../modules'
  end

  # Share a folder to the VM (id, guest path, host path)
  config.vm.share_folder "vagrant-share", "/vagrant-share", "../share"
  config.vm.share_folder "source", "/home/vagrant/home", ENV['HOME']

  # https://gist.github.com/2155825
  config.vm.customize ["modifyvm", :id, "--memory", 1024]
  config.vm.customize ['storagectl', :id, '--name', 'SATA Controller', '--hostiocache', 'on' ]
  config.vm.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1' ]
end
