VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  vm_type = 'plain'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'saucy64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box'

  # Assign this VM a unique hostname
  config.vm.hostname = "#{ENV['USER']}.#{vm_type}.saucy64.vagrantup.com"

  # Forward a port from the guest to the host (id, guest port, host port)
  #config.vm.forward_port 80, 8080, :auto => true
  config.vm.network :private_network, ip: "192.168.33.100"

  config.vm.network "forwarded_port", guest: 22, host: 2220

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifest_file = "#{vm_type}-ubuntu64.pp"
  #   puppet.module_path = '../modules'
  # end

  # Share a folder to the VM (id, guest path, host path)
  # config.vm.synced_folder "../share", "/vagrant-share"
  # config.vm.synced_folder ENV['HOME'], "/home/vagrant/home"

  # https://gist.github.com/2155825
  config.vm.provider :virtualbox do |vb|
    #   # Don't boot with headless mode
    #   vb.gui = true
    #
    # Use VBoxManage to customize the VM. For example to change memory:

    # Set memory allocated to the VM in MB
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    # vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--hostiocache', 'on' ]
    # vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1' ]
  end
end
