VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  vm_type = 'sonar'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'precise64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  # Assign this VM a unique hostname
  config.vm.hostname = "jenkins.#{vm_type}.precise64.vagrantup.com"

#   # Forward a port from the guest to the host (id, guest port, host port)
#   config.vm.forward_port 9000, 9000, :auto => true # Sonar Web interface port
#   config.vm.forward_port 8080, 8090, :auto => true # Jenkins
#   config.vm.forward_port   80, 8080, :auto => true # Apache reverse proxy port
   config.vm.forward_port 49153, 49153, :auto => true # PostgreSQL database port

  config.vm.network :private_network, ip: "192.168.33.20"

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifest_file = "#{vm_type}-ubuntu64.pp"
  #   puppet.module_path = '../modules'
  # end

  config.vm.synced_folder ".", "/share"
  config.vm.synced_folder "../share", "/vagrant-share"
  config.vm.synced_folder "#{ENV['HOME']}/work/kyriba", "/kyriba"
  config.vm.synced_folder "#{ENV['HOME']}", "/myhome"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    #   # Don't boot with headless mode
    #   vb.gui = true
    #
    # Use VBoxManage to customize the VM. For example to change memory:

    # Set memory allocated to the VM in MB
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # config.vm.provision :shell, :path => "bootstrap.sh"

end
